### ISSUE TITLE
[Feat] 장부 관련 API 구현

### ISSUE THREAD

**Issue by JaeHunLee-git** [2024-PKNU-capstone/backend#10]
## Description
장부 API

## Todo
- [x] 장부 엔티티 생성
- [x] 장부 리스트 조회 기능 추가
- [x] 장부 상세 조회 기능 추가
- [x] 장부 등록하기
- [x] 승인 해야할 장부 조회
- [x] 장부 승인 및 반려하기

## ETC
기타사항
