### ISSUE TITLE
[Refactor] 장부 API 리팩토링

### ISSUE THREAD

**Issue by JaeHunLee-git** [2024-PKNU-capstone/backend#29]
## Description
장부 API 리팩토링

## Todo
- [x] fromDate, toDate 동적 쿼리 처리 (QueryDSL)
- [x] 장부 조회 시 학과 ID 받아오는 코드 추가
- [x] 장부 수정 API 추가
- [x] Lazy 로딩 프록시 객체 직렬화 문제 해결

## ETC
기타사항
