### ISSUE TITLE
[Feat] 가입 링크 (초대코드) 생성 로직 추가

### ISSUE THREAD

**Issue by onegqueen** [2024-PKNU-capstone/backend#8]
## Description
유저가 가입시 사용할 초대코드 생성및 처리 로직을 추가한다

## Todo
- [ ] 역할별 가입 로직 변경
- [ ] 초대코드(가입링크) 생성 로직 추가
- [ ] 초대코드로 학과(학교) 식별 로직 추가

## ETC
기타사항
